export const EventItemData = [
  {
    id: 1,
    title: 'Lived Experience Luncheon Series with Dr. Alex Auerbach',
    link: '#',
    location: '405 Robertson Hall',
    time: '8:00 AM - 10:00 AM',
    month: 'Sept',
    day: '15',
    date: '2023-09-15',
    category: 'Faculty',
  },
  {
    id: 2,
    title: 'Science Student Alumni Mixer 2022',
    link: '#',
    location: '405 Robertson Hall',
    time: '2:00 PM - 10:00 PM',
    month: 'Sept',
    day: '18',
    date: '2023-09-18',
    category: 'Current Students',
  },
  {
    id: 3,
    title: 'Milestone Anniversary Celebration 2022',
    link: '#',
    location: '405 Robertson Hall',
    time: '1:00 PM - 3:00 PM',
    month: 'Sept',
    day: '21',
    date: '2023-09-21',
    category: 'Alumni',
  },
  {
    id: 4,
    title: 'Virtual Career Fairs',
    link: '#',
    location: '405 Robertson Hall',
    time: '8:00 AM - 4:00 PM',
    month: 'Sept',
    day: '23',
    date: '2023-09-23',
    category: 'Multi-Day',
  },
];
