name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "develop"
jobs:
  deploy:
    environment:
      name: github-pages
      url: $0
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: dist
        build_command: yarn build
